FROM python:3.11-rc-bullseye


RUN mkdir -p /app
RUN mkdir -p /data

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONUNBUFFERED 1

COPY requirements.txt /app

RUN pip3 install --upgrade pip 

RUN pip3 install --no-cache-dir -r requirements.txt

COPY . /app


ENV FLASK_APP=runProduction.py

EXPOSE 5000

ENTRYPOINT ["gunicorn","--config", "gunicorn_config.py", "runProduction:app"]